-- 1. Retrieve all columns from the customer table.
SELECT 
	customer_id,
    store_id,
    first_name,
    last_name,
    email,
    address_id,
    activebool,
    create_date,
    last_update,
    active
FROM public.customer;

-- 2. Display only film_id, title, and rating from the film table.
SELECT 
	film_id, 
	title, 
	rating
FROM public.film;

-- 3. Retrieve the first 15 records from the actor table.
SELECT
	actor_id,
	first_name,
	last_name,
	last_update
FROM public.actor
LIMIT 15;

-- 4. Retrieve all customers and sort them by last_name in ascending order.
SELECT 
	customer_id,
	first_name,
	last_name
FROM public.customer
ORDER BY last_name ASC;

-- 5. Display payment_id, customer_id, and amount, sorted by amount from lowest to highest.
SELECT 
	payment_id,
	customer_id,
	amount
FROM public.payment
ORDER BY amount ASC;

-- 6. Retrieve customers sorted by:
--     - first_name in ascending order
--     - last_name in descending order
SELECT 
	customer_id,
	first_name,
	last_name
FROM public.customer
ORDER BY first_name ASC, last_name DESC;

-- 7. Retrieve all payments where the amount is greater than 5.
SELECT
	payment_id,
	customer_id,
	staff_id,
	rental_id,
	amount,
	payment_date
FROM public.payment
WHERE amount > 5;

-- 8. Retrieve all payments where the amount is between 3.99 and 6.99.
SELECT
	payment_id,
	customer_id,
	staff_id,
	rental_id,
	amount,
	payment_date
FROM public.payment
WHERE amount BETWEEN 3.99 AND 6.99;

-- 9. Retrieve all customers whose first_name starts with the letter J.
SELECT
	customer_id,
	first_name,
	last_name
FROM public.customer
WHERE first_name LIKE 'J%';

-- 10. Retrieve all films where the description contains the word “Action”.
SELECT
	film_id, 
	title, 
	rating
FROM public.film
WHERE description LIKE '%Action%';

-- 11. Retrieve payments greater than 7, sorted by amount in descending order.
SELECT
	payment_id,
	customer_id,
	staff_id,
	rental_id,
	amount,
	payment_date
FROM public.payment
WHERE amount > 7
ORDER BY amount DESC;

-- 12. Retrieve customers whose first name ends with “n”, sorted alphabetically.
SELECT
	customer_id,
	first_name,
	last_name,
	email
FROM public.customer
WHERE first_name LIKE '%n';

-- 13. Calculate the total amount spent by each customer.
SELECT
	customer_id,
	SUM(amount) AS total_amount
FROM public.payment
GROUP BY customer_id;

-- 14. Retrieve the average payment amount per customer.
SELECT
	customer_id,
	ROUND(AVG(amount), 2) AS average_amount
FROM public.payment
GROUP BY customer_id;

-- 15. Calculate the total revenue generated by each staff member.
SELECT
	staff_id,
	SUM(amount) AS total_revenue
FROM public.payment
GROUP BY staff_id;

-- 16. Identify the top 5 customers based on total payment amount.
SELECT
	customer_id,
	SUM(amount) AS total_amount
FROM public.payment
GROUP BY customer_id
ORDER BY total_amount DESC
LIMIT 5;

-- 17. Find the average film length per release year.
SELECT
	release_year,
	ROUND(AVG(length), 2) AS average_film_length
FROM public.film
GROUP BY release_year;

-- 18. Retrieve the highest single payment amount in the payment table.
SELECT
	MAX(amount) as highest_single_payment
FROM public.payment;

-- 19. Count how many payments each customer has made.
SELECT
	customer_id,
	COUNT(payment_id) AS number_of_payments
FROM public.payment
GROUP BY customer_id;

-- 20. Retrieve customers who are active and sort them by first_name.
SELECT
	customer_id,
	first_name,
	last_name,
	email
FROM public.customer
WHERE active = 1
ORDER BY first_name;